# Generated by Django 3.1.7 on 2021-03-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20210319_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='longName',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='shortName',
            new_name='short_name',
        ),
    ]
