# Generated by Django 3.1.7 on 2021-03-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20210319_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
